# Generated by Django 2.2.12 on 2020-10-26 10:33

import apps.album.models
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('watch_count', models.IntegerField(default=9000, verbose_name='浏览次数')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('desc', models.TextField(verbose_name='图集介绍')),
                ('beauty_name', models.CharField(max_length=30, verbose_name='女神姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('download_url', models.TextField(verbose_name='下载链接')),
                ('download_password', models.CharField(max_length=30, verbose_name='下载密码')),
                ('download_price', models.FloatField(verbose_name='图集价格')),
                ('cover_img', models.ImageField(upload_to=apps.album.models.create_album_folder)),
                ('beauty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='beauty.Beauty')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='AlbumTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(error_messages={'max_length': '最长为40位', 'min_length': '最短是0位'}, max_length=40, verbose_name='图集标签')),
            ],
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=apps.album.models.create_pic_folder)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pic', to='album.Album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(related_name='album_tags', to='album.AlbumTags'),
        ),
    ]
