# Generated by Django 2.2.12 on 2021-03-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210117_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
