# Generated by Django 2.2.12 on 2021-01-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('thumbnail', models.URLField(null=True)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AdRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_record', to='ad.Ad')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='ad.AdCategory'),
        ),
    ]
