# Generated by Django 2.2.12 on 2021-03-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beauty',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
