# Generated by Django 2.2.12 on 2021-03-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_auto_20210325_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beauty',
            name='age',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='beauty',
            name='beauty_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='beauty',
            name='birthday',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='beauty',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beauty',
            name='job',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='beauty',
            name='tall',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='beauty',
            name='weight',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='beauty',
            name='xingzuo',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
